name: MyLocalApp
options:
  deploymentTarget:
    iOS: "16.0"
targets:
  MyLocalApp:
    type: application
    platform: iOS
    sources:
      - ContentView.swift
      - MyLocalApp.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ahmed.MyLocalApp
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: My Local App
        INFOPLIST_KEY_UILaunchScreen_Generation: YES