name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check files
        run: |
          echo "Project files:"
          find . -maxdepth 3 -type f